# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "New Build to App Distribution Beta"
  lane :distribution do
    # sh("flutter build apk --release")
    firebase_app_distribution(
          app: "1:177761251370:android:652e9c80f7202247999353",
          firebase_cli_path: "/usr/local/bin/firebase",
          apk_path: "../android/fastlane/app-release.apk",
          firebase_cli_token: "1//0esQ6rMbovSUUCgYIARAAGA4SNwF-L9Ir4JMTJUEH7TxuZ78A6ohqP6RWHmbhlKR4sYTfi66b6JjMnBh3Wqyg5TpxICJd16p4xYA"
          )

          version_number = firebase_app_distribution_get_version_number
          UI.message("Latest Firebase App Distribution version number: #{version_number}")
  end

  
end
