default_platform(:android)

platform :android do
  desc "Build android app to Firebase distribution"
  lane :distribution do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["CREDENTIAL_FILE_CONTENT"],
      debug:true
    )
    new_version_code = latest_release[:buildVersion].to_i + 1

    # Update version code
    increment_version_code(
      gradle_file_path: "app/build.gradle",
      version_code: new_version_code
    )

    # sh "flutter build apk --flavor newDev -t lib/main.dart"

    # Distribute the new build
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      apk_path: "../android/fastlane/app-release.apk",
      firebase_cli_token: ENV["CREDENTIAL_FILE_CONTENT"]
    )
  end  
end
