name: CI/CD
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - uses: subosito/flutter-action@v2
      #   with:
      #       channel: 'stable'
      # - run: flutter pub get
      # - name: Build
      #   run: |
      #     flutter build apk --flavor newDev -t lib/main.dart

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Install aapt
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk-build-tools

      - name: Check Firebase App Version
        id: check_version
        run: |
        
          # Set the Firebase project using --project and --token options
          firebase use ${{secrets.FIREBASE_APP_ID}} --token "$(firebase login:ci --no-localhost)"

          # Get the latest version from Firebase
          latest_version=$(firebase appdistribution:versions:list --format "value(version)" | head -n 1)

          # Get the version of the APK you are trying to deploy
          new_version=$(aapt dump badging app-release.apk | awk -F"'" '/versionName/{print $2}')

          echo "Latest version from Firebase: $latest_version"
          echo "New version of the APK: $new_version"

          if [ "$latest_version" == "$new_version" ]; then
            echo "Error: The new app version is the same as the current last app version in Firebase."
            exit 1
          fi
            echo ::set-output name=exit_code::$?

      - name: Deploy
        if: steps.check_version.outputs.exit_code == 0
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app-release.apk
          groups: tester
          appId: ${{secrets.FIREBASE_APP_ID}}
